---
title: "Untitled"
author: "Christian Cole"
date: "22/11/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
# libraries
library(readxl)
library(plyr)
library(ggplot2)
library(dplyr)
```

```{r functions}
# functions
## Gives count, mean, standard deviation, standard error of the mean, and confidence interval (default 95%).
##   data: a data frame.
##   measurevar: the name of a column that contains the variable to be summariezed
##   groupvars: a vector containing names of columns that contain grouping variables
##   na.rm: a boolean that indicates whether to ignore NA's
##   conf.interval: the percent range of the confidence interval (default is 95%)
summarySE <- function(data=NULL, measurevar, groupvars=NULL, na.rm=FALSE,
                      conf.interval=.95, .drop=TRUE) {
    # New version of length which can handle NA's: if na.rm==T, don't count them
    length2 <- function (x, na.rm=FALSE) {
        if (na.rm) sum(!is.na(x))
        else       length(x)
    }

    # This does the summary. For each group's data frame, return a vector with
    # N, mean, and sd
    datac <- ddply(data, groupvars, .drop=.drop,
      .fun = function(xx, col) {
        c(N    = length2(xx[[col]], na.rm=na.rm),
          mean = mean   (xx[[col]], na.rm=na.rm),
          sd   = sd     (xx[[col]], na.rm=na.rm)
        )
      },
      measurevar
    )

    # Rename the "mean" column    
    datac <- plyr::rename(datac, c("mean" = measurevar))

    datac$se <- datac$sd / sqrt(datac$N)  # Calculate standard error of the mean

    # Confidence interval multiplier for standard error
    # Calculate t-statistic for confidence interval: 
    # e.g., if conf.interval is .95, use .975 (above/below), and use df=N-1
    ciMult <- qt(conf.interval/2 + .5, datac$N-1)
    datac$ci <- datac$se * ciMult

    return(datac)
}

numericFactorOrder <- function(x) {
    
  u = unique(x)
  new.levels = u[order(as.numeric(u))]
  x = factor(x, levels=new.levels)
  return(x)
  
}

```


## Plotting of Transfer Experiment Results - for ML

```{r readML}
# Read in ML's data
my.dat = read_xlsx("dat/20191030DatasetPaper.xlsx", sheet = "DataMl")

# only use the transfer experiments for Groups 1 & 2. Groups 3-6 are not 
# clear in what they are and don't fit with the rest. Mostly Persistence?
# TODO - deal with Groups 3-6 later
transfer.dat = my.dat %>% filter(Time == "00000" & Group %in% c(1,2)) %>% select(c("Substrate", "ActivityID", "ObsType", "Count", "Mass", "Duration", "Group", "Repeat")) 
transfer.dat

```

```{r}

# fix column types
transfer.dat$Count = as.numeric(transfer.dat$Count)
transfer.dat$Group = as.character(transfer.dat$Group)
transfer.dat$Repeat = as.character(transfer.dat$Repeat)

# add a photoID column to keep track of which datapoint is which
photo.id = rep(paste0("P", seq(1:5)), as.integer(nrow(transfer.dat)/5+1))
transfer.dat = data.frame(PhotoID = photo.id[1:nrow(transfer.dat)], transfer.dat)

# split out each set of photos...
p1 = transfer.dat %>% filter(PhotoID == "P1") %>% select(Mass,Duration,Group,Repeat,Count)
p2 = transfer.dat %>% filter(PhotoID == "P2") %>% select(Mass,Duration,Group,Repeat,Count)
p3 = transfer.dat %>% filter(PhotoID == "P3") %>% select(Mass,Duration,Group,Repeat,Count)
p4 = transfer.dat %>% filter(PhotoID == "P4") %>% select(Mass,Duration,Group,Repeat,Count)
p5 = transfer.dat %>% filter(PhotoID == "P5") %>% select(Mass,Duration,Group,Repeat,Count)

# ...and merge
merge.dat = data.frame(p1, p2$Count, p3$Count, p4$Count, p5$Count)
names(merge.dat) = c("Mass","Duration","Group","Repeat","P1","P2","P3","P4","P5")

# calculate the Transfer Ratios and Efficiencies
# NB: the summarise() function can be problematic here, if plyr is loaded
#     after dplyr. Check that first if this stops working.
final.dat = merge.dat %>% group_by(Mass, Duration, Group, Repeat) %>% summarise(Donor = P3 - P1, Receiver = P5 - P2, Donor_post = P3 - P4) %>% mutate(Ratio = Receiver/Donor, Efficiency = Receiver/Donor_post)

summ.dat = summarySE(final.dat, measurevar = "Ratio", groupvars = c("Group"))

```

```{r plotML}

ggplot(summ.dat, aes(x = Group, y = Ratio)) + 
  geom_point(size=2.2) +
  geom_errorbar(aes(ymin = Ratio-se, ymax = Ratio+se), width = 0.08) +
  geom_point(colour = "white") +
  scale_x_discrete(labels = c("Wool", "Nylon")) +
  labs(x = "Receiver Material",
       y = "Transfer Ratio")

```

## Read BH Data

```{r readBh}
# Read in Bh's data
my.dat = read_xlsx("dat/NorBhCleanDataset.xlsx", sheet = "Data", trim_ws = TRUE, col_types = "text")

# Fix the column name for Time - seems to have extra spaces
my.dat = rename(my.dat, Mass = `Mass (g)`)
my.dat = rename(my.dat, TransferTime = `TransferTime (s)`)
my.dat = rename(my.dat, PersistenceTime = `PersistenceTime (min)`)
#colnames(my.dat)

# only use the Transfer data (PersistenceTime == "0") 
transfer.dat = my.dat %>% filter(PersistenceTime == 0) %>% select(c("Substrate", "ObservationType", "Count", "Mass", "TransferTime", "Experiment", "Replicate")) 
transfer.dat

```
```{r}
# fix column types
transfer.dat$Count = as.numeric(transfer.dat$Count)
transfer.dat$Experiment = as.character(transfer.dat$Experiment)
transfer.dat$Replicate = as.character(transfer.dat$Replicate)

# add a photoID column to keep track of which datapoint is which
photo.id = rep(paste0("P", seq(1:5)), as.integer(nrow(transfer.dat)/5+1))
transfer.dat = data.frame(PhotoID = photo.id[1:nrow(transfer.dat)], transfer.dat)

# split out each set of photos...
p1 = transfer.dat %>% filter(PhotoID == "P1") %>% select(Mass,TransferTime,Substrate,Experiment,Replicate,Count)
p2 = transfer.dat %>% filter(PhotoID == "P2") %>% select(Mass,TransferTime,Substrate,Experiment,Replicate,Count)
p3 = transfer.dat %>% filter(PhotoID == "P3") %>% select(Mass,TransferTime,Substrate,Experiment,Replicate,Count)
p4 = transfer.dat %>% filter(PhotoID == "P4") %>% select(Mass,TransferTime,Substrate,Experiment,Replicate,Count)
p5 = transfer.dat %>% filter(PhotoID == "P5") %>% select(Mass,TransferTime,Substrate,Experiment,Replicate,Count)

# ...and merge
merge.dat = data.frame(p5[,c("Mass","TransferTime","Substrate","Experiment","Replicate")], p1$Count, p2$Count, p3$Count, p4$Count, p5$Count)
names(merge.dat) = c("Mass","TransferTime","Substrate","Experiment","Replicate","P1","P2","P3","P4","P5")

# calculate the Transfer Ratios and Efficiencies
# NB: the summarise() function can be problematic here, if plyr is loaded
#     after dplyr. Check that first if this stops working.
final.dat = merge.dat %>% group_by(Mass, TransferTime, Substrate, Replicate) %>% summarise(Donor = P3 - P1, Receiver = P5 - P2, Donor_post = P3 - P4) %>% mutate(Ratio = Receiver/Donor, Efficiency = Receiver/Donor_post)

ratio.dat = summarySE(final.dat, measurevar = "Ratio", groupvars = c("Mass","TransferTime","Substrate"))

ratio.dat
```
```{r}

ggplot(ratio.dat, aes(x = numericFactorOrder(TransferTime), y = Ratio)) + 
  geom_point(size=1) +
  geom_errorbar(aes(ymin = Ratio-se, ymax = Ratio+se), width = 0.08) +
  geom_point(colour = "white", size = 0.7) +
#  scale_x_discrete(labels = c("Wool", "Nylon")) +
  labs(title = "Analysis of Transfer Ratio",
       x = "Transfer Time (s)",
       y = "Transfer Ratio") +
  facet_grid(numericFactorOrder(Mass) ~ Substrate)


```
```{r}

eff.dat = summarySE(final.dat, measurevar = "Efficiency", groupvars = c("Mass","TransferTime","Substrate"))

eff.dat
ggplot(eff.dat, aes(x = numericFactorOrder(TransferTime), y = Efficiency)) + 
  geom_point(size=1) +
  geom_errorbar(aes(ymin = Efficiency-se, ymax = Efficiency+se), width = 0.08) +
  geom_point(colour = "white", size = 0.7) +
#  scale_x_discrete(labels = c("Wool", "Nylon")) +
  labs(title = "Analysis of Transfer Efficiency",
       x = "Transfer Time (s)",
       y = "Efficiency") +
  facet_grid(numericFactorOrder(Mass) ~ Substrate)


```

## SG Data


```{r readSg}
# Read in Bh's data
my.dat = read_xlsx("dat/StrSgCleanDataset.xlsx", sheet = "Data", trim_ws = TRUE, col_types = "text")

# Fix the column name for Time - seems to have extra spaces
my.dat = rename(my.dat, Mass = `Mass (g)`)
my.dat = rename(my.dat, TransferTime = `TransferTime (s)`)
my.dat = rename(my.dat, PersistenceTime = `PersistenceTime (min)`)
#colnames(my.dat)

# only use the Transfer data (PersistenceTime == "0") 
transfer.dat = my.dat %>% filter(PersistenceTime == 0) %>% select(c("Substrate", "ObservationType", "Count", "Mass", "TransferTime", "Experiment", "Replicate"))

# also remove expt 16 as it is incomplete
transfer.dat = transfer.dat[as.numeric(transfer.dat$Experiment) < 16,]

transfer.dat

```


```{r}
# fix column types
transfer.dat$Count = as.numeric(transfer.dat$Count)
transfer.dat$Experiment = as.character(transfer.dat$Experiment)
transfer.dat$Replicate = as.character(transfer.dat$Replicate)

# add a photoID column to keep track of which datapoint is which
photo.id = rep(paste0("P", seq(1:5)), as.integer(nrow(transfer.dat)/5+1))
transfer.dat = data.frame(PhotoID = photo.id[1:nrow(transfer.dat)], transfer.dat)

# split out each set of photos...
p1 = transfer.dat %>% filter(PhotoID == "P1") %>% select(Mass,TransferTime,Substrate,Experiment,Replicate,Count)
p2 = transfer.dat %>% filter(PhotoID == "P2") %>% select(Mass,TransferTime,Substrate,Experiment,Replicate,Count)
p3 = transfer.dat %>% filter(PhotoID == "P3") %>% select(Mass,TransferTime,Substrate,Experiment,Replicate,Count)
p4 = transfer.dat %>% filter(PhotoID == "P4") %>% select(Mass,TransferTime,Substrate,Experiment,Replicate,Count)
p5 = transfer.dat %>% filter(PhotoID == "P5") %>% select(Mass,TransferTime,Substrate,Experiment,Replicate,Count)

# ...and merge
merge.dat = data.frame(p5[,c("Mass","TransferTime","Substrate","Experiment","Replicate")], p1$Count, p2$Count, p3$Count, p4$Count, p5$Count)
names(merge.dat) = c("Mass","TransferTime","Substrate","Experiment","Replicate","P1","P2","P3","P4","P5")

# calculate the Transfer Ratios and Efficiencies
# NB: the summarise() function can be problematic here, if plyr is loaded
#     after dplyr. Check that first if this stops working.
final.dat = merge.dat %>% group_by(Mass, TransferTime, Substrate, Replicate) %>% summarise(Donor = P3 - P1, Receiver = P5 - P2, Donor_post = P3 - P4) %>% mutate(Ratio = Receiver/Donor, Efficiency = Receiver/Donor_post)

ratio.dat = summarySE(final.dat, measurevar = "Ratio", groupvars = c("Mass","TransferTime","Substrate"))

ratio.dat
```

```{r}

ggplot(ratio.dat, aes(x = numericFactorOrder(TransferTime), y = Ratio)) + 
  geom_point(size=1) +
  geom_errorbar(aes(ymin = Ratio-se, ymax = Ratio+se), width = 0.08) +
  geom_point(colour = "white", size = 0.7) +
#  scale_x_discrete(labels = c("Wool", "Nylon")) +
  labs(title = "Analysis of Transfer Ratio",
       x = "Transfer Time (s)",
       y = "Transfer Ratio") +
  facet_grid(numericFactorOrder(Mass) ~ Substrate)


```

```{r}

eff.dat = summarySE(final.dat, measurevar = "Efficiency", groupvars = c("Mass","TransferTime","Substrate"))

eff.dat
ggplot(eff.dat, aes(x = numericFactorOrder(TransferTime), y = Efficiency)) + 
  geom_point(size=1) +
  geom_errorbar(aes(ymin = Efficiency-se, ymax = Efficiency+se), width = 0.08) +
  geom_point(colour = "white", size = 0.7) +
#  scale_x_discrete(labels = c("Wool", "Nylon")) +
  labs(title = "Analysis of Transfer Efficiency",
       x = "Transfer Time (s)",
       y = "Efficiency") +
  facet_grid(numericFactorOrder(Mass) ~ Substrate)


```

## EM Data

```{r readEm}
# Read in Em's data
my.dat = read_xlsx("dat/StrEmCleanDataset.xlsx", sheet = "DataEm", trim_ws = TRUE, col_types = "text")

# Fix the column name for Time - seems to have extra spaces
my.dat = rename(my.dat, Mass = `Mass (g)`)
my.dat = rename(my.dat, TransferTime = `TransferTime (s)`)
my.dat = rename(my.dat, PersistenceTime = `PersistenceTime (min)`)
#colnames(my.dat)

# only use the Transfer data (PersistenceTime == "0") 
transfer.dat = my.dat %>% filter(PersistenceTime == 0) %>% select(c("Substrate", "ObservationType", "Count", "Mass", "TransferTime", "Experiment", "Replicate"))

# also remove expt 16 as it is incomplete
transfer.dat = transfer.dat[as.numeric(transfer.dat$Experiment) < 16,]

transfer.dat

```

```{r}
# fix column types
transfer.dat$Count = as.numeric(transfer.dat$Count)
transfer.dat$Experiment = as.character(transfer.dat$Experiment)
transfer.dat$Replicate = as.character(transfer.dat$Replicate)

# add a photoID column to keep track of which datapoint is which
photo.id = rep(paste0("P", seq(1:5)), as.integer(nrow(transfer.dat)/5+1))
transfer.dat = data.frame(PhotoID = photo.id[1:nrow(transfer.dat)], transfer.dat)

# split out each set of photos...
p1 = transfer.dat %>% filter(PhotoID == "P1") %>% select(Mass,TransferTime,Substrate,Experiment,Replicate,Count)
p2 = transfer.dat %>% filter(PhotoID == "P2") %>% select(Mass,TransferTime,Substrate,Experiment,Replicate,Count)
p3 = transfer.dat %>% filter(PhotoID == "P3") %>% select(Mass,TransferTime,Substrate,Experiment,Replicate,Count)
p4 = transfer.dat %>% filter(PhotoID == "P4") %>% select(Mass,TransferTime,Substrate,Experiment,Replicate,Count)
p5 = transfer.dat %>% filter(PhotoID == "P5") %>% select(Mass,TransferTime,Substrate,Experiment,Replicate,Count)

# ...and merge
merge.dat = data.frame(p5[,c("Mass","TransferTime","Substrate","Experiment","Replicate")], p1$Count, p2$Count, p3$Count, p4$Count, p5$Count)
names(merge.dat) = c("Mass","TransferTime","Substrate","Experiment","Replicate","P1","P2","P3","P4","P5")

# calculate the Transfer Ratios and Efficiencies
# NB: the summarise() function can be problematic here, if plyr is loaded
#     after dplyr. Check that first if this stops working.
final.dat = merge.dat %>% group_by(Mass, TransferTime, Experiment, Substrate, Replicate) %>% summarise(Donor = P3 - P1, Receiver = P5 - P2, Donor_post = P3 - P4) %>% mutate(Ratio = Receiver/Donor, Efficiency = Receiver/Donor_post)

ratio.dat = summarySE(final.dat, measurevar = "Ratio", groupvars = c("Mass","TransferTime","Substrate"))

knitr::kable(ratio.dat)
```

Added an extra column for "Experiment" in addition to "Substrate" here as there seems to be too many replicates?? Need to investigate further.

```{r}

ggplot(ratio.dat, aes(x = numericFactorOrder(TransferTime), y = Ratio)) + 
  geom_point(size=1) +
  geom_errorbar(aes(ymin = Ratio-se, ymax = Ratio+se), width = 0.08) +
  geom_point(colour = "white", size = 0.7) +
#  scale_x_discrete(labels = c("Wool", "Nylon")) +
  labs(title = "Analysis of Transfer Ratio",
       x = "Transfer Time (s)",
       y = "Transfer Ratio") +
  facet_grid(numericFactorOrder(Mass) ~ Substrate)


```
```{r}

eff.dat = summarySE(final.dat, measurevar = "Efficiency", groupvars = c("Mass","TransferTime","Substrate"))

eff.dat
ggplot(eff.dat, aes(x = numericFactorOrder(TransferTime), y = Efficiency)) + 
  geom_point(size=1) +
  geom_errorbar(aes(ymin = Efficiency-se, ymax = Efficiency+se), width = 0.08) +
  geom_point(colour = "white", size = 0.7) +
#  scale_x_discrete(labels = c("Wool", "Nylon")) +
  labs(title = "Analysis of Transfer Efficiency",
       x = "Transfer Time (s)",
       y = "Efficiency") +
  facet_grid(numericFactorOrder(Mass) ~ Substrate)


```